name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Configure GPG
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
        gpg --list-secret-keys --keyid-format LONG
    
    - name: Build and test
      run: mvn clean compile test
    
    - name: Generate sources and javadoc
      run: mvn source:jar javadoc:jar
    
    - name: Publish to Maven Central
      run: mvn clean deploy -P release
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    
    - name: Verify deployment
      run: |
        echo "Deployment completed successfully!"
        echo "Check Sonatype Nexus: https://s01.oss.sonatype.org/"
        echo "Once released, artifacts will be available at:"
        echo "https://repo1.maven.org/maven2/io/github/arvinu/kafka-management-library/"
